title: MAIN-VC
description: IMPROVE ADAPTIVE INSTANCE NORMALIZATION VOICE CONVERSION WITH MUTUAL INFORMATION

theme: jekyll-theme-cayman

github:
  repository_url: https://github.com/PecholaL/MAIN-VC
