title: MAIN-VC
description: LIGHTWEIGHT SPEECH REPRESENTATION DISENTANGLEMENT WITH MUTUAL INFORMATION FOR VOICE CONVERSION

theme: jekyll-theme-cayman

github:
  repository_url: https://github.com/PecholaL/MAIN-VC
